### ISSUE TITLE
A8下午回忆

### ISSUE THREAD

**Issue by ghost** [ThyrixYang/nju_cs_kaoyan#1]
先问了两个英语问题：1.你最喜欢的计算机科学家 2.介绍你的项目
接着问了：堆的建立和插入，删除，又问了一个经典数学问题，给你一组数有n个，用0到n-1填充，有一个数重复了，请找出来
最后问了，介绍一个你觉得物联网的课设实验

**Comment by ThyrixYang** [comment]
已添加，谢谢
