### ISSUE TITLE
经验贴by Polarsun

### ISSUE THREAD

**Issue by ghost** [ThyrixYang/nju_cs_kaoyan#3]
想了想，还是发一个经验贴吧，毕竟考研不易！
1>	英语（65）：自己的英语就很差，六级大概考了4次才过吧，在3月份决定考研的时候，，每天就下载了一个 扇贝 背单词，每天坚持200个，一直持续到5月中旬，个人觉这样效果不太好了，就开始拿着新东方的联想词根记忆法 开始背了，每天一个list。就这样坚持到10月份，过了两三遍吧，10月份来时这段时间基本都是上午背单词，到10月份以后我就是拿着另外一本好像是朱伟的单词书开始吧，一直坚持到考试前，这后单词都是早上，晚饭后背的。期间英语在6月中旬的时候就开始做真题的，每天一到两篇阅读吧，有时状态不好，就做一篇，自己的准确率很低，英语我大概就是这样过来的。英语就要靠积累，单词背的多了，阅读就能读懂了。
2>	数学（101）：数学是从4月份开始的，当时买了同济七版的数学教材，每天就开始抄书，抄概念，做课后习题，到六月中旬才搞完这些，开始做李永乐复习全书，数学我都是放在下午的，目标每天看个20页吧。一直到8月中旬才看完，然后就开始做了概率论和线代的辅导讲义（强烈推荐）还有张宇的1000题（只做数学部分，宇哥题目难，所以我数学部分没做完），到10月底就差不多看完了。数学真题（2000-2017）我10月中旬开始做的，早上8点半-11点半做一份真题，对一下答案，第二天开始整理错题（准备一个错题本）。就两天一份吧，到11月10号差不多就可以做完了，然后开是看 李永乐的真题解析书，（之前做的试卷都是买的试卷），这样就很费时间了，知识点比较多，都是集中在一起的，每天也差不多20页吧。到12月10号就可以看完，但是这时候大家都比较紧张，比较累。所以一定要坚持，后面10多天就开始看错题笔记，把以前的试卷拿出来再做吧，1000题数学部分没做完，就在抽着补几道。数学就是这样熬过来的。
3>	政治（60）：个人复习比较差，9月中下旬（差不多10月初）才开始，没报班，每天下午开始做，看精讲精练，1000 题，真题，最后做了个8套卷，4套卷，看了腿姐的总结，肖佬的时政。个人复习很差，此处就不多说。
4>	专业课（105）：这个考每个学校的都不一样。我考CS，我们有5门专业课（实际上有4门），专业课都是在晚上看的，每门每天10-15页吧，直接做的王道的参考资料，只有一本是王道没有，计算机系统基础和配套的题册（一定要看），最后王道有2本过了两遍（OS,DS），计网过了一遍，计算机系统基础看了2遍，中间刷过好多网传的贵校的卷子，历年真题吧。
复试：
笔试，离散和编译原理，2月25返的学校，然后断断续续看了离散（主要是看了学长以前给我的笔记和借了学妹的笔记），反正笔试也是基本不会，编译原理看了 中科大 陈意云的视频课（强烈推荐，看到35节差不多），能那个80%的分数吧，说句实话，基本没好好准备，因为之前一直以为自己不会进复试。
机试，本科期间打过一段ACM。不过自己战绩很差，没有咸鱼大佬那样的实力（膜咸鱼大佬），最后AC了两道（这个个人建议，初试完不管成绩如何都开始练吧，找工作，复试都用的到）。
面试，准备了简历，自我介绍啥（中英文，最后完全没用上），老师问的也就是数据结构居多吧
总结：个人属于比较浪的那种，最后擦线进的这种，算是幸运的吧，本科是物联网工程，算是半个跨考吧，反正考得几门专业课，只学过计网（忘得一干二净的），就都是和大家一样（都是小白）重新开始学吧！最喜欢的一句话送给后来的人：你不努力，总有人会实现你的梦想！

**Comment by ThyrixYang** [comment]
已经添加，谢谢
