### ISSUE TITLE
经验贴by斗芽

### ISSUE THREAD

**Issue by lovygit** [ThyrixYang/nju_cs_kaoyan#4]
政治（65）：
	一般听学长学姐都说政治准备不需要特别提前，实践告诉我，真理往往还是掌握在大多数人的手上啊~~ 我也是快十月份才订了肖秀荣老师的资料，开始做的就是选择题，每天大概做两个小时吧，这个一般根据自己的情况。把看政治的时间合理规划一下，我开始安排在晚饭之后，不过去了图书馆，确实是犯困啊！后来调整到下午。到了后面离考试一个月内，就可以准备准备大题了。这个我个人感觉就是背书啊，具体的就是背题。我选择的就是肖的四套卷。八套卷也是做了的，主要是保持感觉吧。不过按照这次考试来看，背了肖四的第一套卷大题基本就ok了（亏我背的那么流利，舍友也轻轻松松就65，小郁闷^-^）。时政的话，这个关注一下当前的一些重大事件，我感觉是差不多了，况且肖四最后的这四套压轴题目已经包括了很多大概率要出的时政大题，所以问题不大。
然后就是考试前一个周，我每天在宿舍背诵肖四一个小时吧，再去图书馆。个人感觉好多人都在图书馆背诵，效果会打折扣，能去一个安静的地方自然更好，不一定是宿舍。然后是晚上回来，再背两个小时（舍友对我真的好啊，没打我），以至于后来四套卷随便问一个问题，我立马就可以顺利背诵出答案，还是很自豪的，有木有~~
考试的时候，做大题还是要答题工整，看交卷的时候，有些同学太潦草，怎么可能高分呢！总之，这门课，认认真真65+还是不难的。

英语（69）：
	我英语本来就不好，虽然也不算很差。记单词这个是个长期工程，已经有好多方法了，这个根据个人情况学习吧，不过英语考高分与词汇量是否大，个人感觉关系不太大。我分数虽然不高，但是单词整体来说记忆的还是挺不错的，用了新东方的绿皮书，不过后来又换成了朱伟的那本绿皮书，个人推荐后者，他的视频我也有看，这个我一般每天早上出宿舍看了半个小时。然后就是重中之重的阅读理解了，主要就是用的张剑的资料，分析的挺好的。这个我现在回头想，还是自己没有规划好的，阅读理解还真的应该从前往后做，最好留几套最近几年的真题模拟一下，效果可能更好。这个工作自己规划吧，我每天没个准，大概就是做三四个阅读题目吧。然后就是很重要的作文了！我个人特别喜欢朱伟的那本红书，王江涛的那本书，我感觉适合基础确实比较差的，他的作文我整体读起来感觉太chinese了。朱伟老师的红书大概分析了十年左右的作文题吧，英语一、二的都有，确实是精品。句式，单词用的都很考究，我也是每天花时间阅读这本红书，培养自己的语感，后来基本上也是可以背诵下来了。这个也是有视频的，我一般放到晚上看的。根据这个结果来看，我作文分数应该不算低。新题型，以及前面的完形填空这个我就没什么经验了，多做一些题体会体会，完形填空的分数一般提高到一个点就基本稳定了，不需要强求自己。

数学（111）：
	个人对这个结果还是不太满意啊（目标130+，我还是太naive）呜呜~~ 我开始刷了李永乐的660题，然后是分阶习题册，后来感觉时间还有很多，又买了张宇的1000题，挑着做的。参考书张宇的，李永乐的都买了，不过后来选择用张宇的，感觉他讲解知识更生动吧。他的视频我没有怎么看，感觉看书效率高一些，里面也有好多他的总结，十分不错。这个我个人建议需要先把数学教材看好，目的是对数学概念有比较深刻的理解，这个真的很重要，非常重要！！！然后就是每天刷3个小时左右的题目吧，保持感觉。还有一点就是一定要看错题，做题的一个很重要的目的就是找漏洞啊，不然你做那么多题目，为了算着好玩呢？后期大概也是一个半月吧，可以买一套历年的真题了，这个一定要定时做，开始不能按时做完关系不大，后来就自然快起来了，既为了查漏补缺，也训练做题的节奏感。真题最好每天安排一套，也不用多做，一直做到考试前一两天我觉得挺合适的。准备工作做好了以后，就是战术问题了，今年我差点崩盘，还是心态有问题，开始遇到好多题目不能立刻做出答案，就开始慌了，幸亏后面hold了，所以心态也是一个重要因素啊。

专业课（130）
	这个分数确实让我意外。南大专业课挺多，算法可能大家都是很关心的，不过呢，考试考的不是特别难的，学习数据结构这门课的时候，基本包含了要考的主要算法了，另外的一些边边角角其实不是那么重要，要是时间紧张，就跳过吧，问题不大。我是因为大二就开始自学数据结构，又把推荐书籍殷人昆老师的课本，以及习题解答都看过了，基本上本科基础的数据结构知识挺清楚了，今年试卷数据结构分数比重相当大，我要没记错应该是有5道大题，这个确实需要你对一些数据结构，还有算法有一些理解了，死记硬背肯定不能做好。另外一个挺重要的就是计算机系统了，袁阿姨的那本书，还有她的习题解答一定要好好看啊，我反正是看了有三遍吧。今年机组一道大题20+分，好好看了也基本是送分题了。操作系统这个，参考课本看了（字太多了，我没有太仔细看），也看了王道单科的书。这个整体上不会出什么大问题。网络这个，我真的没发言权啊，怕是我好多分都丢在了这里，也是自己不太重视吧，不过确实因为占分不大，我就把王道单科书看了两三遍。

后记：
	整个考研过程，毕竟说到底是自己的战斗，是一个人的冲锋！所以，你选择了，就要一直坚持。我在这个过程中也是有很多的担忧的，这都是很正常的。其实，真的是那句话，你努力了，考上也真的是时间问题了。愿你们一样能够收获硕果，我们南大相见吧~

感谢：
	感谢老朱、老李！我们的三人讨论组让我不仅仅收获了知识，也让我不再孤独。也感谢2018南大CS劝退群的大家，陪伴我学习与进步。

**Comment by Pinkman026** [comment]
膜375大佬

**Comment by SnowyJune973** [comment]
已添加，375大佬太强啦！
