### ISSUE TITLE
学渣355+逆袭南大cs学硕

### ISSUE THREAD

**Issue by xiezilailai** [ThyrixYang/nju_cs_kaoyan#5]
2018年2月6日</br></br>
&emsp;&emsp;考研过去了将近一个半月，成绩公布后的第三天。之所以现在才写经验贴，是因为一直没什么时间。前一段时间毕设开题答辩一团糟，找工作也不是很顺利。355+分还是有些出乎意料，仿佛看到了一片曙光，分数不高不低，甚至没法确定是否能够进入复试，如果大家看到这篇帖子，也就说明初试过了（没错，我就是这么爱玩）。

2018年3月30日</br></br>
（复试结束半个月，复试通过，学硕排名前十被录取）</br>
下面开始分享一下这几个科目我的复习方法，按照考试顺序进行：</br></br>
## 政治一（60+）</br></br>
&emsp;&emsp;讲实话，政治算是我比较慌的一门，因为从小记性不好，文科很烂，而且个人来讲读书很少，大学快毕业写出来的东西和小学相比感觉没什么进步（从这篇经验贴的文笔不难看出）。如果你有和我同样的顾忌，请你相信我，考研政治很简单，**紧跟肖秀荣爷爷**就对了。不管每年考前大家怎么传，题目怎么漏，请你记住，你爷爷永远是你爷爷。肖爷爷出一本书你就买一本，政治你要做的就是一开始对照着最厚的那本全书（名字是精讲精练），做一遍肖爷爷的1000题，做完之后再看几遍（至少一遍吧）。后面会出一本《知识点提要》，是一些比较重要的知识点，不可能全部背住，但请你尽可能熟悉。再后面的时政是一本小书，买来翻翻看看就好！《命题人讲真题》要当考试一样自己独立完成选择题，大题可以不看。《肖八肖四》选择题和上一本一样，一定要独立完成，再看答案！**大题请你全部背住，全部背住，全部背住**！（如果你实在记不住，也要把**每道题答的那些点记一下**，考试的时候编，但为什么要尽可能背呢，因为书上某些话某些词逼格更高一些，你可能编不出来）。另外，选择题看答案的时候，请你搞清楚自己为什么做错，将所有选项以及这个题涉及的知识点以及关联知识点，全部找出来看一遍，久而久之，你的知识体系也就建立起来了。我就是这样做的，每天政治就早晚各花半个小时到一个小时看一下，即使我有着金鱼记忆，最后还是考了60多，相信你们可以做的更好。</br></br>

## 英语一（70+）</br></br>
&emsp;&emsp;英语的话只要你基础不是特别特别差，把单词背背，真题做做，作文练练，肯定不会拖你后腿，再说英语本来就不是用来拉分的。单词书的话新东方的绿皮书、红皮书或者是恋恋有词，都是可以的，而且买一本就够了，不需要都买。真题的话个人推荐华研外语的真题（你去淘宝一搜就出来了），里面真题真的很多，好多真题比我们年龄还大。推荐做法是最老的那几年比较简单，做着练手，可以不卡时间，每天做两篇就好。最近几年的，请你留下来到考试前一个月再做，那时请你务必算好时间，从阅读到写作都要完成。至于中间那些年的，可以自行安排，每天做几篇也可以，或者卡时间做也可以。</br></br>
&emsp;&emsp;个人感觉英语毕竟是一门语言，不需要你用什么奇淫技巧，**语言需要用心去感受，也就是我们常说的找语感**，当你看到对应的翻译后总是无法理解时，不需要纠结过多，把你自己想象成为一个外国人，你就是用这种方式在讲话，记录下来，多练习几次，自然也就熟悉了。还有那些常用的词组句型搭配，最好用个本子记录下来，有时间要多翻一翻。</br></br>
&emsp;&emsp;至于作文，个人推荐王江涛的作文书，里面范文有很多，当然你能背几篇最好。如果实在背不下来，就**找出里面用到的句式或者好的搭配，并把它们记录下来，抽时间用这些自己造造句子，加深印象**。</br></br>
&emsp;&emsp;个人**不建议买张剑的黄皮书**，我买过一本二手的看了看，废话实在太多了，怎么可能有那么多时间翻那本书，除非你英语真的一点也不会，四级过的都很吃力那种，倒是可以跟着那本书慢慢学。我觉得华研那本书答案还是比较详细的，有些答案其实不必太过较真，尽力理解就好。</br></br>
&emsp;&emsp;还有就是**不建议大家买那些模拟题**，不管是谁出的模拟题都不如真题，相信我真题够你做好长时间的（前提是你认认真真的做下去）。
</br></br></br>
2018年4月4日</br>
## 数学一（115+）</br></br>
&emsp;&emsp;你或许会好奇为什么第二天才考数学和专业课，相信我，如果第一天考这两门，上午数学考完，下午可能就没什么人去了。好多人说考研基本就是考数学，emmm，有点夸张，但是不得不说，如果你数学考得很不错，基本考研是稳的（除非你其他科目有没过线的）。拿今年举例，数学偏难的年份，没考上的同学基本都是数学崩了，好多考内的同学数学也是在90附近，南大学硕排名前32的同学平均分也只有99分，这也是我今年考上最主要的原因，靠数学奶了一口。

&emsp;&emsp;数学我看的比较早，大三下学期（就是你们现在）就抽时间在**过课本**，如果你想过课本的话，有我们学校的教材就够了，不需要买其他书。过课本也没什么技巧，很随性的那种，就是基本概念捋一捋，课后习题尽量每种类型都做一下，如果你时间充足的话，就把微积分、线性代数和概率论都过一下。我去年因为在争取保研，大三下几门课压力很大，所以时间不多，所以只看了微积分，不过现在回过头想想，后面刷全书会稍微轻松一些。</br></br>
&emsp;&emsp;等这个学期考试结束（我记得最后一门是马克思），就可以正式进入复习状态了。第一件事就是刷全书，全书我用的是李王（李永乐、王式安）的那本，因为是数学一所以里面微积分、线代、概率论都有，按顺序先刷一遍，刷的方式因人而异，我当时的做法就是概念勾一下，尽可能背一下，例题尽量自己动手跟着算一下，可以看着书上的答案算，这个没关系，关键是你要动手，不要光看。还要就是，**一定要把你认为难的、还有非常难的题做标记**，等你下次看的时候就会有重点，什么意思呢？比如我就会经常在一道解法很骚的那种题目旁边打好几个星星，有时会写“鬼能算出来”、“鬼能想到这么做”之类，等下次看时会有印象。你可以自己规划好一天看几页，我记得暑假结束半个月前我第一遍就已经过完了。刷完第一遍可以找些题做了，我当时做的是张宇1000题，其实现在想想很后悔，那个题有点偏，作用不大，这里我**推荐你们做李王那一套里面的那本660**，里面的题难度适中，有点考研题目的感觉。做的时候，规定时间（我一般是每天上午）做几十道（那个上面都是选择和填空），然后开始对答案，不会做的做错的，都要勾出来，可以找个错题本记录下来，有空翻一翻。</br></br>
&emsp;&emsp;然后这本做的差不多了，就可以做真题和模拟题了，真题推荐张宇的真题大全解，考研历年所有题目都有，2002年之前的可以做的随意一些，因为比较简单，会做就好。但是2002年之后的请你注意，**一定要卡时间做，一定要卡时间做，一定要卡时间做**，就每天上午的8:30-11:30，整整三个小时，不要翻书（你可能会说有些公式啥的你没记住，这不是借口，请你提前把三门数学的所有公式总结出来，平时也要注意将常用的套路添加到上面去），少喝水，这三个小时尽量别上厕所。对答案和之前一样，也是要把一些技巧性很强的题还有你算错的题都记录到错题本上去。**模拟题推荐合工大的卷子**（超越、共创，我后面有网盘链接，你也可以网上买，淘宝有卖），题目难度中等偏上，我后悔的是这个卷子我做的不算太多，做的时候和真题一样要记得卡时间，你可以隔几天做做真题，隔几天做做这个模拟卷子。我是非常非常**不推荐大家买张宇的四套卷和八套卷**，题目太偏，没有任何意义，我曾经买过8套卷，做了四张，加起来都没150分。。。</br></br>
&emsp;&emsp;还有一份概率论的资料，是我在网上找到的，我也曾经推荐给我一位关系很好的同学，他也觉得很好用，是**张伟老师的资料**（后面有链接），链接里有两个文件，厚的那个是解析，薄的那个是题目，你要先自己做一遍题目，上面的题目都是有一定难度的，不会做很正常，然后记得把解析上的东西搞清楚。这本资料我觉得总结的非常好，概率论有些混乱的地方都解释的非常非常清楚，有时间你可以多刷几遍。如果你有不懂的地方可以去找这个老师的网课（链接里面那个是比较老的），他的这份资料好多题没有变，b站上有他最近几年的视频，记得搜“概率论张伟”（搜张伟，爱情公寓那个会蹦出来）。总之，数学是大头，一定要多花些时间在上面！</br></br>

## 专业课845（105+）</br></br>
&emsp;&emsp;前面提到有些学校考408，南大考的是845，所以**第一件事你就要确定你到底考哪个学校**，专业课看哪些书。这里的时间节点大家一定要注意，你最好在暑假前先确定一下，因为如果你考专业课是408的学校或者像南大这种考5门的学校，你最好暑假就开始看它们的推荐教材。暑假过后就一定要确定下来，因为后面马上要报名，你越到后面换学校，可能麻烦就越多。

&emsp;&emsp;好的，现在假如你已经确定报了南大，我介绍一下我每门科目的复习方法以及复习资料，仅供参考！

&emsp;&emsp;**数据结构**：建议购买推荐教材以及对应的课后习题书籍，王道可以不买，数据结构南大不会考一些太偏的东西，把**基础的那些掌握就可以**。带星号的内容算法可以不看，但是概念要记清楚，记得17好像考出来几个概念，是带星号章节中的内容。

&emsp;&emsp;**算法**：这里**不推荐大家购买那本英文教材**（大佬除外），劝退群（最后有群号，里面群文件很多干货）里面有英文的ppt，内容不多，这个ppt结合黄宇的那本算法就已经足够了，如果你还觉得慌，可以刷一下群文件那个算法练习题，没有答案并且题目有一定难度，适合有余力的同学做，但是近两年的845的算法题从里面都能找到。算法这一块其实不用花太多时间，前两年好像都是一个选择题一个大题，并且今年大题的难度和分值都有所下降，我个人就是在算法方面花了太多时间，结果今年发现那题好简单。去年大题是一个求连通分量的算法，有一定难度（那题是我前面提到的算法练习题里面的原题），并且有10分，今年那道我记得好像没有十分的样子（记不清了，好像没有10分吧）。

&emsp;&emsp;**计网**：计网推荐结合王道一起看，教材可以不看，东西太多了。**王道结合谢希仁的ppt**（劝退群群文件有）差不多了，计网知识点比较零碎，要多记，可以做一些408的题目做练习。

&emsp;&emsp;**计算机系统基础**：推荐购买教材以及习题指导，尤其是那本习题指导一定要买，每年的大题和选择题基本都是原题。不建议看王道的那本计组，还是有区别的。课本过1-2遍，看不懂的地方可以去慕课或者b站看袁阿姨的视频（袁阿姨语速有点慢，1.5倍速播放最佳）。推荐把**习题指导的题目每种类型都做一遍，重要的题目多做几遍**（怎么知道重不重要呢？去看前两年的题目，考的基本就是那点东西）。

&emsp;&emsp;**操作系统**：建议购买推荐教材，并且过2-3遍，操作系统也是内容比较固定，推荐搭配王道，可以尝试着做一下课后习题，这个没有答案，群里好像有一部分答案，而且正确性不能保证。**操作系统还是要熟悉内容，把常见的题目做熟**，比如说pv那一块，分页机制等等。

&emsp;&emsp;其实我做的并不好，专业课只考了105左右，105分是南大学硕前32名同学的平均水平，不高不低，我一直将其归功于自己记性真的不好，好多零碎的点我记不熟，有几道大题废了。今年专业课总体比去年好很多，希望大家认真复习，多花些时间在上面，争取突破120分！

## 总体时间规划

&emsp;&emsp;下面是我的时间规划，这个因人而异，你们可以当做参考，我的时间比较紧，基本就是整整坐一天（当然能学多少东西就不一定了），如果你做不到这么紧可以把时间调松一些。

&emsp;&emsp;**这个学期最后一门考试结束之前：**</br>
&emsp;&emsp;背背单词、过高数课本做课后习题（抽时间做就好，如果你争取保研的话，学期课程为主，如果专心考研，花的时间可以多一点）
</br></br>
&emsp;&emsp;**这个学期最后一门考试结束之后：**</br>
&emsp;&emsp;早上8点或者9点开始看书都可以，晚上学到8点就行，因为我们学校暑假8点教室就关门了，回宿舍学不进去也没关系（我就是这样，捂脸）。</br>
&emsp;&emsp;开始做数学全书、刷英语前几年的真题、背英语单词、政治的话可以不看、专业课看课本和ppt</br></br>
&emsp;&emsp;**离大四开学还有半个月到一个月：**</br>
&emsp;&emsp;看书时间不变</br>
&emsp;&emsp;做660题目，英语继续刷题、背单词、政治开始看着精讲精练做1000题，专业课和以前一样

&emsp;&emsp;**9月和10月：**</br>
&emsp;&emsp;看书时间：7点/8点-晚上10点，每周休息天数建议不超过两天，最好半天到一天</br>
&emsp;&emsp;9点之前：政治:做1000题或者第二遍看1000题 英语：背单词、看自己的笔记</br>
&emsp;&emsp;9点-11点半：看数学，前期可以接着做660或者看自己的错题集，后期可以把开始时间提早半小时卡时间做真题或者模拟题</br>
&emsp;&emsp;2点-5点/5点半：看专业课，做题也好，刷ppt做笔记也好
晚上-10点：看英语和政治，内容和早上类似

&emsp;&emsp;**最后两个月：**</br>
&emsp;&emsp;看书时间不变</br>
&emsp;&emsp;8点半之前：政治背知识点或者肖八肖四，英语不变</br>
&emsp;&emsp;8点半-11点半：卡时间做题，或者总结之前做过的题，可以交叉着来，每天做一样
下午不变
晚上和早上类似

## 选择学校的问题

&emsp;&emsp;说一下我为什么选择南大。本人来自国内某末流985，实际上选择并不多（假设你想考更好的学校），清北交不考虑（太难考了），复旦不是很推荐（复旦计算机讲实话一般般，除非你喜欢这所学校或者想去上海发展），哈工大计算机感觉没有另外几所好（个人感觉，你可以喷我，哈工大专硕招的人比较多，属于性价比高那种，可以考虑一下），另外太冷了那边，北航蛮不错（我查过一点资料，北航复试刷人貌似有点狠，你们可以再仔细查一下），不过我不喜欢北京，所以直接pass掉，浙大我下面会详细谈，中科大比起来还是要差一点（中科大主要是理科强，工科差一些），所以我选择南大。

&emsp;&emsp;大家经常比的还是南大和浙大，我也专门分出一段来谈一下自己的观点。浙大有几个好处就是报的时候你不需要纠结学硕专硕，最后统一排名，另外复试的机试可以用pat代替（也就是说你可以提前刷分）。浙大和南大三门都一样，政治一、英语一、数学一，专业课浙大考408，南大考845,学弟学妹们可以找前几年的题试一下，408是统考，王道的书就是专门对付408的，网上相关的资料也要多一些，408的题给人的感觉是你就是不知道这题到底想干嘛，或者就是算不对，找不到做题方法。845的题感觉就是题目并不难，就是知识点太多，到最后考的时候好多地方还是没掌握好（毕竟有五门）。个人来讲更喜欢845，这个因人而异，大家可以自己找真题感受一下。从今年的形势来看，浙大彻底爆炸，浙大计算机确实比南大强一些，但是初试362的分数线还是蛮高的，并且复试被刷的人也很多；相比起来，南大今年学硕录取初试最低分329，专硕录取初试最低分304，性价比要远远高于浙大。所以你们这一届报南大的同学应该会变多吧！

## 学硕和专硕的问题
&emsp;&emsp;南大学硕和专硕是分开的，不能相互调剂，这就是一个博弈问题，我今年就是这样捡了便宜，因为好多高分大佬不敢报学硕（当时南大说学硕招12个，专硕 39个），所以最后用355+的成绩冲进了学硕前十名（这逼够装一辈子）。今年的情况又要具体分析，这个学长也帮不了你们，具体年份具体分析，刺不刺激。但总体上肯定还是，学校越好越难考，学硕比专硕难考。非全的话，不管别人怎么说，社会怎么议论，**个人不推荐**你们读，因为我觉得门槛低，含金量不高，所以我不看好。

## 网课和补习班的问题
&emsp;&emsp;关于网课我的建议是除非有些东西你真的是一点也看不懂，这时网课肯定是效果很好的。否则，网课会很占用你的时间，政治没必要看网课，看肖秀荣的书背肖八肖四就ok，数学的话之前看过一点张宇讲线面积分的部分（那一块有点抽象），还有张宇讲线性代数最开始的梳理，讲的比较清晰，这两个大家推荐大家网上看一下（后面有网盘链接）。英语的话，一般不需要，如果你语感不好，可以看看朱伟的视频（后面有网盘链接，b站也有），当然不要浪费太多时间在上面。</br>
&emsp;&emsp;报班的话其实没多大必要，特别是你有自己的计划，报班可能会起反作用。报班适合那些基础特别差，完全没计划，完全不知道什么时候该干嘛的同学。我曾经报过一个整治押题班，讲真没什么用，老师上课讲了几个段子还蛮搞笑，除此之外还不如背背肖八肖四。

## 复习场地以及复习伙伴的问题
&emsp;&emsp;如果你想考上，**不要待在寝室复习，不要待在寝室复习，不要待在寝室复习**。建议在图书馆或者教室等学习氛围浓厚的地方复习。</br>
&emsp;&emsp;复习伙伴的话，你可以和你靠谱一点的基友一起，最好不要超过四个人（靠谱一点就是坐的住的那种）；不建议和你关系不稳定的异性同学两个人复习，没有开玩笑，毕竟考研是对你们未来影响比较大的一件事，不要被其他事情分心；当然了，你也可以像我这样，耐得住寂寞，自己单干。

## 心态问题
&emsp;&emsp;虽然放在后面说这个，last but not least，心态应该说是最重要的。只有良好的心态，上面的所有操作才能生效，否则考研考着考着可能人就没了。。。心态分为两方面吧，一方面是复习时的心态，另一方面是考试时的心态。</br>
&emsp;&emsp;我们先说第一方面，这个我比较有发言权，相信没有几个人比我心态更炸裂吧!我是大三时候正处于保研边缘，所以大三的专业课都很用心，这个学期的课程是百分之百投入的，前面说的过高数课本的时间其实都是挤出来的，自己基本没有什么玩的时间，要不在教室上课，要不在图书馆看书，还和同学搞信安大赛（最后gg）。大三结束专业课成绩出来发现排名还是原地踏步，处于边缘而且没有保研加分，所以暑假待在学校每天复习，七月那几天遇到点事，烦的要死，将近半个多月没看进书，但还是硬着头皮没回家在学校按计划复习到了暑假最后一天。别人一般都是10月或者11月进入考研疲倦期，我基本一开学就进入了这种状态，尤其是每天下午一开始看专业课，心态炸裂的感觉每天至少经历一次。加上9月底保研结果出来，刚好差一名保送（别笑），郁闷了挺长时间。心态炸裂最好的解决方法就是，**和你同学倾诉**（不过我一般不这么做，因为负面情绪实在太多）；另外就是实在**不想看书就放松一下，别把自己逼太紧**，今天太累就回去睡一觉，明天会好很多，感觉我就是这样。当然如果你实在受不了，请你放弃，考研不是唯一的出路。</br>
&emsp;&emsp;另一方面，为防止考试时的心态炸裂，平时做题必须**卡时间**，尤其是数学，拿我举例子，因为后面基本每隔一天模拟一套真题或者合工大的模拟题，心态炸裂是常事，每次都有好多题毫无头绪，所以考试的时候即使题难也基本没什么感觉，能够将自己正常的水平发挥出来！</br>

## 其他忠告
&emsp;&emsp;多查资料，尽早决定报考学校</br>
&emsp;&emsp;每天多喝水，按时吃饭，**一定要吃早饭**，否则上午没效率。</br>
&emsp;&emsp;中午要午休，半个小时最佳，晚上吃完饭可以趴一会</br>
&emsp;&emsp;晚上尽量不要熬夜，回到寝室可以玩一到两个小时，最晚不要超过12点半睡觉</br>
&emsp;&emsp;**考研要静心**，其他的事情请先放一放（考驾照啊，搞对象啊什么的，前三年干嘛去了，非得大四啊）</br>
&emsp;&emsp;出去复习时，**能不拿手机就不要拿手机**，这一点非常重要（最后两个月我是没拿过手机的）</br>
&emsp;&emsp;考研期间少打游戏，尤其是**睡觉之前，千万不能玩游戏**，可以看看剧看看小说什么的</br>
&emsp;&emsp;B站是个好地方，好多网课都可以在上面找到</br>
&emsp;&emsp;错题本什么的可以不用买本子，买一些A4纸，自己钉起来，要划算的多！</br>
&emsp;&emsp;草稿纸直接买一堆，推荐我当时买的那个，可以两面用（后面有淘宝链接，我没打广告）</br>
</br></br>
&emsp;&emsp;差不多就是这些吧！谢谢学弟学妹们能够耐着性子看到最后，希望对你们有所帮助。考研不是唯一的出路，但如果你不想工作或者觉得前途一片迷茫，它确实是一个很好的选择。但凡选择就要承担相应的后果，所有美好的事物都是值得我们去追求的，不是吗？在二十几岁的时候，有梦就应该去追，不要害怕自己做不成某件事，因为你可能这辈子一事无成，不差这一件（滑稽脸）！毕业前攒点人品，希望我顺利毕业！也祝考研的学弟学妹们金榜题名，学有所成！

## 推荐书籍资料

**政治推荐的书籍资料**：</br>
肖爷爷全套

**英语推荐的书籍资料**：</br>
华研真题25年</br>
恋恋有词/新东方考研单词绿皮书</br>
王江涛 考研英语高分写作</br>
朱伟恋恋有词视频 https://pan.baidu.com/s/1fF2-pUfnE4QsNrMQkwUzgg</br>

**数学推荐的书籍资料**：</br>
强烈推荐：</br>
&emsp;李王全书</br>
&emsp;李王660</br>
&emsp;张伟讲义 https://pan.baidu.com/s/1OMAjGoR9gyJrFylRFajwEg</br>
&emsp;合工大历年模拟题 https://pan.baidu.com/s/1Wz6vBZBBYgUqRyD-Ldd_0Q</br>
&emsp;张宇真题大全解</br>
可选：</br>
&emsp;张宇2017年网课（最前面分析2016年数学一那一段很搞笑，推荐）
https://pan.baidu.com/s/1MjZdJV4mBBEoihpzNe_lBA</br>
&emsp;张宇高数18讲（这本书当作补充可以翻翻，里面有一些解题技巧）</br>
&emsp;毛纲源 考研数学常考题型解题方法技巧归纳（这本书我没怎么看，技巧总结的很好）</br></br>
**其他资料**：</br>
&emsp;&emsp;	南大cs劝退群：550150534</br>
&emsp;&emsp;张雪峰 介绍考研（纯属娱乐，推荐）
https://www.bilibili.com/video/av18976919?from=search&seid=6554244525854097925
</br>&emsp;&emsp;草稿纸
https://item.taobao.com/item.htm?spm=a1z09.2.0.0.420f2e8d2JGP7b&id=528631760220&_u=5229u88r5838

													--蝎子莱莱 2018年4月5日

**Comment by ThyrixYang** [comment]
已经添加，谢谢

**Comment by lovygit** [comment]
姜大佬太用心了！给你打calld(`･ω･´)b赞
